### ISSUE TITLE
SecuritySpy Camera Streams appear to be about 2.5 days delayed

### ISSUE THREAD

**Issue by LukeSpad** [Ghawken/HomeKitLink-Siri#21]
When viewing streams from security spy I appear to have a delay of around 2 and a half days based on the time stamp on the feed. I think you had said it was necessary to impose a delay on the feed but I wonder if the padding is larger than intended?

**Comment by Ghawken** [comment]
Hi

Think you will be misreading things - not sure we could buffer for 2 1/2 days even if wanted to!

“Viewing Streams” == image or live video ?

If static image:
Basically what happens though is when requested by a HomeKit App (and ONLY when requested - otherwise would be hammering away transferring a lot of image data from camera servers) a image is pulled from cameras and saved as a local file.
This takes 2 requests cycle to be shown in the HomeKit App.  Have described this elsewhere in detail. (Probably forum)

So if return to your HomeKit app after a few days - you will potentially see the old image, until 2 request cycles have passed (typically cycle = 10 seconds, or 60 seconds) and then current image will be present.

Was considering removing old image after a period of time (?24 hours) and defaulting to default image - which would remove this type of confusion.  May still be best way to do it… 

If live video stream:
Time stamp is straight from security Spy - so nothing to do with HomeKit plugin.  

Suspect though you are referring to images as above.

**Comment by Ghawken** [comment]
Hopefully above answers.
Closing this.
