### ISSUE TITLE
HKLS Error Message:  Attempted Pair Verify Without Being Paired to HKL Bridge

### ISSUE THREAD

**Issue by trwesq** [Ghawken/HomeKitLink-Siri#28]
---
name: HomeKitLink Siri Error Message
about: Unexpected message appearing in Indigo
title: HKLS Error:  Attempted Pair Verify without being paired to HKL Bridge nnnnnn first.
labels: ''
assignees: ''

---

**Describe the bug**
5 of my 10 HKLS bridges report back the below error message several times per day.  HKLS and Indigo are unaffected -- everything works as expected but it would be nice to have any error messages!

**To Reproduce**
No particular steps taken.  Just running the HKLS plugin and getting these messages.

**Expected behavior**
Not expecting to have any error messages while running HKLS Bridge.

**Screenshots**
HomeKitLink Siri Error          (hap_handler.py: Function: _pair_verify_two  line: 547):    Error :  Message : ('192.168.1.45', 50634): Client 065ba670-6da8-48c6-bb08-7eb6925dc343 attempted pair verify without being paired to HomeKitLink Bridge 316862 first.
  
**Additional context**
I have had this problem crop up since using HKLS.  I have deleted devices and deleted bridges and started all over, but these error message continue in many of my bridges.  The content of the bridges is about the same:  Switches and Lights mainly.  Nothing unique about the bridges that are reporting the error messages.

**Comment by Ghawken** [comment]
Hi

Normally, this will relate to updating the Homekit architecture to 16.4 which has recently become available on 27th March.

If you have devices, hubs, appleTV, mac’s that access HomeKit and haven’t been updated, or are unable to update then this message will be repeatedly received until you update.   It comes from the client for every bridge you have - its the client that is the problem and needs to be tracked down.  In the case of your error message client is 192.168.1.45

What normally happens with the Homekit architecture update is you receive this message once for the client in particularly (for every bridge you have - so can be multiple red lines if have multiple brigdes) - and then they verify and it goes.   

With devices that are not compatible with the new Homekit, this message continues until you remove Home app from them and/or logout.

Alternatively - something has gone wrong with earlier architecture update for this homekit client - which has been seen multiple times before and one of the reasons the 16.2 update was pulled by apple, until it recent return.   In this case -  Log out, log in again sometimes work.  Occasionally it can relate to home icloud caching, and that appears eventually go away.  Since you have deleted bridges - that won’t be the issue.

Seeing you have deleted bridges and restarted - it will be because the client in question has not upgraded to HomeKit new architecture.  (? not compatible).  You should have received a warning message from the Home app when you upgraded.

Glenn
