### ISSUE TITLE
Changing device type doesn't automatically update in HomeKit

### ISSUE THREAD

**Issue by durosity** [Ghawken/HomeKitLink-Siri#9]
**Describe the bug**
When changing the type of a device from one to another (eg Switch to Blind) saving will cause the existing device in HomeKit to show as 'not responding'. 

**To Reproduce**
Publish a device to HomeKit as a switch -> Save -> Observe working within Home app
Edit device in Indigo -> Change type to a different type, eg Blinds -> Save
Device shows as Not Responding in Indigo

**Expected behavior**
Updates to new device type

**Additional context**
Work around:  Unpublished device -> Save, then re-publish device -> Save and it'll reappear correctly.  Perhaps this could be automated when the device type changes to avoid user confusion?

**Comment by Ghawken** [comment]
Yes - that is expected and actually covered in the documentation…..

Well least I thought it was - can’t find it currently. :(

Thankfully it is pretty recoverable with unpublished device - as this was previous horrible error that often would mean need to delete all devices/bridge start again.

Yes - if you change device types - you need to unpublish device, save, Save Config dialog (restarting Bridge) and then check in HomeKit App gone, and re-add device.

Pretty hard to automate.. although will have a think.  Early on was against having unneeded bridge restarts (turn on the debug logging and see what happens when we shut down/restart - remembering that this plugin is doing everything; no external software running).    Have to close homekit driver, homekit bridge accessory and the complete driver thread - and all the attached accessories….   But that has been working really well for some time - so probably shouldnt be so wary.

Still will need to be unpublished, bridge restarted and then new device published, bridge added.  Can’t imagine can do all that in config dialog time limit - and probably better to leave as is.  Although may see if can lock device type unless unpublished - that should be doable.
